spring.application.name=email-writer-sb

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
gemini.api.key=AIzaSyC92-ma8oS41bgWirfakcGZVzsoPe5myEg
gemini.retry.max-attempts=5
gemini.retry.initial-backoff-ms=1000
server.port=8081